console.log("refacto1");
console.log("refacto2");
console.log("Hello World!!!!");
console.log("hello Samy");
console.log("hello Samy2");
console.log("hello Samy3");
console.log("hello Samy4");
console.log("refacto1");
console.log("refacto2");
console.log("Hello World!!!!");
console.log("hello Samy");
console.log("hello Samy2");
console.log("hello Samy33");
console.log("hello Samy4");
console.log("edit rebase i");
const d = 10;
const e = 11;
const a = 1;
const b = 2;
const c = 3;
